# Generated by Django 2.1.7 on 2019-09-06 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='', max_length=20, verbose_name='用户真实姓名')),
                ('card_id', models.CharField(default='', max_length=30, verbose_name='身份证')),
                ('face_photo', models.ImageField(default='', upload_to='IDNumber/%Y/%m/%d', verbose_name='身份证人脸照')),
                ('word_photo', models.ImageField(default='', upload_to='IDNumber/%Y/%m/%d', verbose_name='身份证国徽照')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '认证信息',
                'verbose_name_plural': '认证信息',
                'db_table': 'yz_AuthUser',
            },
        ),
    ]
